server:
  port: 8091
  servlet:
    context-path: /o2o
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/o2o?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: pp123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /html/
      suffix: .html


mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.example.o2o.domain

logging:
  level:
    com:
      example:
        o2o:
          mapper: debug

pagehelper:
  helperDialect: mysql
  reasonable: true #开启优化，<1页返回第一页
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql